import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: 270,
  },
  homeContainer: {
    flexGrow: 1,
    height: '100%',
  },
  homeImageBackground: {
    width: '100%',
    height: 270,
  },
  homeImageStyle: {
    borderBottomRightRadius: 65,
  },
  darkOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: 270,
    backgroundColor: '#000',
    opacity: 0.2,
    borderBottomRightRadius: 65,
  },
  searchContainer: {
    paddingTop: 100,
    paddingLeft: 16,
  },
  userGreet: {
    fontSize: 38,
    fontWeight: 'bold',
    color: 'white',
  },
  userText: {
    fontSize: 16,
    color: 'white',
  },
  searchBox: {
    marginTop: 16,
    backgroundColor: '#fff',
    paddingLeft: 24,
    padding: 12,
    borderTopRightRadius: 40,
    borderBottomRightRadius: 40,
    width: '90%',
  },
  searchIcon: {
    position: 'absolute',
    top: 25,
    right: 60,
    opacity: 0.6,
  },
  menuIcon: {
    position: 'absolute',
    top: 40,
    left: 16,
  },
  bellIcon: {
    position: 'absolute',
    top: 40,
    right: 30,
  },
  headingWrapper: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headingText: {
    fontSize: 22,
    fontWeight: 'bold',
  },
  actionLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#ff6200',
  },
  topTrendingListContainer: {
    paddingVertical: 20,
    paddingLeft: 16,
  },
  trendingImages: {
    width: 150,
    marginRight: 8,
    height: 250,
    borderRadius: 10,
  },
  imageOverlay: {
    width: 150,
    height: 250,
    marginRight: 8,
    borderRadius: 10,
    position: 'absolute',
    backgroundColor: '#000',
    opacity: 0.2,
  },
  imageLocationIcon: {
    position: 'absolute',
    marginTop: 40,
    left: 10,
    bottom: 10,
  },
  imageText: {
    position: 'absolute',
    color: 'white',
    marginTop: 4,
    fontSize: 14,
    left: 30,
    bottom: 10,
  },
  recentContainer: {
    marginBottom: 60,
  },
  recentVisitedImage: {
    width: '92%',
    height: 250,
    borderRadius: 10,
    alignSelf: 'center',
  },
  recentVisitedMapPinWrapper: {
    position: 'absolute',
    bottom: 0,
    padding: 16,
  },
  imageLocationRecentIcon: {
    marginLeft: 10,
    position: 'relative',
    top: 4,
    marginHorizontal: 10,
  },
  imageTextRecent: {
    fontSize: 22,
    color: 'white',
    marginBottom: 10,
  },
  imageDescription: {
    fontSize: 14,
    color: 'white',
    marginBottom: 4,
    opacity: 1,
    marginLeft: 16,
  },
  postImageContainer: {
    backgroundColor: 'white',
    flex: 1,
  },
  postImageWrapper: {
    height: 380,
    justifyContent: 'flex-end',
  },
  postImage: {
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  tagLine: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    marginVertical: 6,
    paddingHorizontal: 14,
  },
  placeName: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
    paddingHorizontal: 14,
    marginBottom: 30,
  },
  backButton: {
    position: 'absolute',
    left: 20,
    top: 40,
    backgroundColor: '#f66200',
    padding: 10,
    borderRadius: 40,
  },
  favouriteButton: {
    position: 'absolute',
    right: 20,
    top: 40,
    backgroundColor: '#f66200',
    padding: 10,
    borderRadius: 40,
  },
  bookTicketButton: {
    position: 'absolute',
    right: 12,
    top: 350,
    backgroundColor: '#ff6200',
    padding: 16,
    borderRadius: 40,
    elevation: 5,
  },
  bookTicketText: {
    color: 'white',
    fontSize: 14,
  },
  postDescription: {
    paddingHorizontal: 14,
    fontSize: 14,
    fontWeight: 'normal',
    opacity: 0.3,
    justifyContent: 'flex-start',
    textAlign: 'justify',
  },
  suggestionImage: {
    width: 150,
    height: 150,
    marginHorizontal: 10,
    borderRadius: 10,
  },
  suggestImageLocationIcon: {
    marginHorizontal: 14,
    marginTop: 4,
    position: 'absolute',
    left: 10,
    bottom: 10,
  },
  suggestImageLocationText: {
    marginHorizontal: 14,
    marginTop: 4,
    position: 'absolute',
    left: 30,
    bottom: 10,
    color: 'white',
    fontSize: 14,
  },
  darkOverlaySuggest: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    width: 150,
    height: 150,
    backgroundColor: '#000',
    opacity: 0.2,
    borderRadius: 10,
    marginHorizontal: 10,
  },
})

export default styles
